# Generated by Django 5.0.7 on 2024-07-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_speciality_options_alter_speciality_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='subjects',
            field=models.ManyToManyField(related_name='speciality', to='course.subject'),
        ),
    ]
